# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7a7e38a4fbffa549e14f99c13cc9c4b7217d89413b4e59f12c4f0895625d9637687271298bd8368fab5ca63325818bb8af7fbdac6464a48dbcfbcbd57c1b609

test:
  secret_key_base: 76c24f250e74542fa5fa854c09a16d60035c3e1c81c0ce8dd8ac2086d1c8eb8ae3b73869ffb9b4d9f95545261cd57b86821fec16132b62d4f8a8c71a1e683590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
