# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ef511843c830bd13749cb61911be8a0958a21d349075372d3325cf5a32842a06b1fe9b32f073e7793ea6181b78c927387d4f92550075dc88df33c85cf7eff60

test:
  secret_key_base: 36f98d7ebb04ca768bbe4227d9a8634be67ad3347447cc714f1a693fab78c1db6be8b044e92ee3630b46f7e637426629291a683b1b9b84ccf6fe20b210dca058

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
